version: '3.8'

services:
  web:
    build: ./backend
    command: bash entrypoint.sh
    volumes:
      - ./backend/src:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:6.2-alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    command: redis-server /usr/local/etc/redis/redis.conf

  celery:
    build: ./backend
    command: celery -A celery_worker.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./backend/src:/app

volumes:
  redis_data:
